### ISSUE TITLE
[1.2.0-RC] WebSocket renderer doesn't work

### ISSUE THREAD

**Issue by Pakisan** [Pakisan/jasyncapi-idea-plugin#16]
I use WebServerPageConnectionService#fileRequested for reload preview on specification changes. After creation of `1.2.0` release I decided to check it on new versions, not only on 2021.2. 

Error occurred when I open preview on 2021.2.2 because of changing of method signature.

```
java.lang.NoSuchMethodError: 'java.lang.CharSequence org.jetbrains.builtInWebServer.liveReload.WebServerPageConnectionService.fileRequested(io.netty.handler.codec.http.FullHttpRequest, java.util.function.Supplier)'
	at com.asyncapi.plugin.idea._core.AsyncAPISchemaHtmlRenderer.render(AsyncAPISchemaHtmlRenderer.kt:54)
	at com.asyncapi.plugin.idea.extensions.web.StaticServer$process$resourceHandler$1.handle(StaticServer.kt:47)
	at com.asyncapi.plugin.idea.extensions.web.StaticServer.handleRequest(StaticServer.kt:88)
	at com.asyncapi.plugin.idea.extensions.web.StaticServer.process(StaticServer.kt:74)
```

In 2021.1 - 2021.2.1 is:
```kotlin
fun fileRequested(request: FullHttpRequest, fileSupplier: Supplier<out VirtualFile?>): CharSequence?
```

In 2021.2.2 - 2021.2.3 is:
```kotlin
fun fileRequested(request: FullHttpRequest, onlyIfHtmlFile: Boolean, fileSupplier: Supplier<out VirtualFile?>): CharSequence?
```

Signature was changed in `2021.2.2 (build 212.5284)`

> WebServerPageConnectionService.fileRequested's signature was changed in 2021.2.2 (build 212.5284)

Use reflection for calling for proper method. `com.intellij.openapi.application.ApplicationInfo#getFullVersion` helps to know which IDEA is using plugin.

I chose it because signature won't be changed in future, and it easier than maintain two releases

> > Is current signature final variant in 2021.2.3 and will not change in next releases like 2021.3, 2022.*? If so I will left It on a place.
>
> Yes, it won't be changed, at least backward compatibility won't be broken, so please feel free to use it. 

References:
- [Question on JetBrains portal](https://intellij-support.jetbrains.com/hc/en-us/community/posts/4409255232786-WebServerPageConnectionService-fileRequested-signature-was-changed-in-2021-2-3?page=1#community_comment_4409282865938)

**Comment by Pakisan** [comment]
How to prevent in future:

- Don't forget to add new versions of IDEA in plugin verification settings
```gradle
tasks.getByName<org.jetbrains.intellij.tasks.RunPluginVerifierTask>("runPluginVerifier") {
    ideVersions.set(listOf(
        "2021.1",
        "2021.1.1",
        "2021.1.2",
        "2021.1.3",
        "2021.2",
        "2021.2.1",
        "2021.2.2",
        "2021.2.3"
    ))
    verifierVersion.set("1.268")
}
```

Will allow to catch compatibility problems:
```
2021-11-10T23:53:02 [main] INFO  verification - Finished 1 of 8 verifications (in 2.2 s): IC-212.5080.55 against com.asyncapi.plugin.idea:1.2.0+idea2021: Compatible
2021-11-10T23:53:02 [main] INFO  verification - Finished 2 of 8 verifications (in 2.3 s): IC-212.5457.46 against com.asyncapi.plugin.idea:1.2.0+idea2021: 1 compatibility problem
2021-11-10T23:53:02 [main] INFO  verification - Finished 3 of 8 verifications (in 2.3 s): IC-212.5284.40 against com.asyncapi.plugin.idea:1.2.0+idea2021: 1 compatibility problem
2021-11-10T23:53:02 [main] INFO  verification - Finished 4 of 8 verifications (in 2.3 s): IC-212.4746.92 against com.asyncapi.plugin.idea:1.2.0+idea2021: Compatible
2021-11-10T23:53:02 [main] INFO  verification - Finished 5 of 8 verifications (in 2.4 s): IC-211.7142.45 against com.asyncapi.plugin.idea:1.2.0+idea2021: Compatible
2021-11-10T23:53:02 [main] INFO  verification - Finished 6 of 8 verifications (in 2.4 s): IC-211.6693.111 against com.asyncapi.plugin.idea:1.2.0+idea2021: Compatible
2021-11-10T23:53:02 [main] INFO  verification - Finished 7 of 8 verifications (in 2.4 s): IC-211.7442.40 against com.asyncapi.plugin.idea:1.2.0+idea2021: Compatible
2021-11-10T23:53:02 [main] INFO  verification - Finished 8 of 8 verifications (in 2.4 s): IC-211.7628.21 against com.asyncapi.plugin.idea:1.2.0+idea2021: Compatible
Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-212.5080.55: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-212.5457.46: 1 compatibility problem
Compatibility problems (1):
    #Invocation of unresolved method org.jetbrains.builtInWebServer.liveReload.WebServerPageConnectionService.fileRequested(FullHttpRequest, Supplier) : CharSequence
        Method com.asyncapi.plugin.idea._core.AsyncAPISchemaHtmlRenderer.render(io.netty.handler.codec.http.FullHttpRequest request, java.lang.String schemaUrl) : java.lang.String contains an *invokevirtual* instruction referencing an unresolved method org.jetbrains.builtInWebServer.liveReload.WebServerPageConnectionService.fileRequested(io.netty.handler.codec.http.FullHttpRequest, java.util.function.Supplier) : java.lang.CharSequence. This can lead to **NoSuchMethodError** exception at runtime.
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-212.5284.40: 1 compatibility problem
Compatibility problems (1):
    #Invocation of unresolved method org.jetbrains.builtInWebServer.liveReload.WebServerPageConnectionService.fileRequested(FullHttpRequest, Supplier) : CharSequence
        Method com.asyncapi.plugin.idea._core.AsyncAPISchemaHtmlRenderer.render(io.netty.handler.codec.http.FullHttpRequest request, java.lang.String schemaUrl) : java.lang.String contains an *invokevirtual* instruction referencing an unresolved method org.jetbrains.builtInWebServer.liveReload.WebServerPageConnectionService.fileRequested(io.netty.handler.codec.http.FullHttpRequest, java.util.function.Supplier) : java.lang.CharSequence. This can lead to **NoSuchMethodError** exception at runtime.
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-212.4746.92: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-211.7142.45: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-211.6693.111: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-211.7442.40: Compatible
    Plugin can be loaded/unloaded without IDE restart

Plugin com.asyncapi.plugin.idea:1.2.0+idea2021 against IC-211.7628.21: Compatible
    Plugin can be loaded/unloaded without IDE restart
```

Settings were extended in #17
